[package]
name = "bst"
version = "24.20.121"
authors = ["Michele Maione <mikymaione@hotmail.it>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"