[package]
name = "bst"
version = "20.19.1223"
authors = ["Michele Maione <mikymaione@hotmail.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"